### PR TITLE
Feature: Added zonwering STTR and Intro

### PR DESCRIPTION
**Pull request by robinpiets**
- Added IntroPage with (optimized) images
- Added STTR + config

An alternative for loading the images inside the App could be loading them directly from the Amazon bucket: `src="https://sttr-files.flolegal.app/00000001002564440000/Uitleg_Luik.png"`

### CODE REVIEW

**Comment by robinpiets** [comment]
Auto label didn't work...

**Review by svenjens — APPROVED** [review]

**Comment by svenjens** [comment]
> An alternative for loading the images inside the App could be loading them directly from the Amazon bucket: `src="https://sttr-files.flolegal.app/00000001002564440000/Uitleg_Luik.png"`


We don't have access to the bucket right? \

**Comment by afjlambert** [comment]
Pushing the images to the repo works fine.
Did you try to optimize them? They seem quite large, pngcrush works great.
Code is 👌🏻

**Review by afjlambert — APPROVED** [review]
See comment about image file size.

**Comment by robinpiets** [comment]
> See comment about image file size.

Good point!

image

**Pull request merged**
