### PR TITLE
Fixed bugs with going to new checkers

### PR DESCRIPTION
**Pull request by robinpiets**
There was a bug when going to a new checker with the same address. The `setTopicData` hook function is not working there because it's going to need to set data for _another_ topic. When updating the `session` with `setSession` directly, it doesn't update the `topicData` hook data. Therefore I needed to force the the new `topicData` in `SessionContext`.

I've already tested this, but please test again by going through multiple checkers with the `NewCheckerModal`

### CODE REVIEW

**Comment by afjlambert** [comment]
The bug seems to be fixed.
I do however see a new bug. See screencast.

https://trello-attachments.s3.amazonaws.com/5e6e7da5939a956434c7bafb/5fb23e756b277f6b020454c7/0a7bec2d0540e2c3ddd41f261e8b4aa7/bug-with-new-checker-modal.mov

**Review by afjlambert — CHANGES_REQUESTED** [review]
The bug seems to be fixed.
I do however see a new bug. See screencast.
Never mind the 'undefined' in this review, that bug is already part of the target branch.

https://trello-attachments.s3.amazonaws.com/5e6e7da5939a956434c7bafb/5fb23e756b277f6b020454c7/0a7bec2d0540e2c3ddd41f261e8b4aa7/bug-with-new-checker-modal.mov

**Comment by afjlambert** [comment]
I get an error while reloading the intro-page. @robinpiets 

Reproduce:
- Clear sessionstorage
- Open `http://localhost:3000/dakraam-plaatsen`
- Reload window
- `Error: topicData.type ('') is not equal to slug ('dakraam-plaatsen')`

Am I missing something?

**Comment by robinpiets** [comment]
> I get an error while reloading the intro-page. @robinpiets
> 
> Reproduce:
> 
> * Clear sessionstorage
> * Open `http://localhost:3000/dakraam-plaatsen`
> * Reload window
> * `Error: topicData.type ('') is not equal to slug ('dakraam-plaatsen')`
> 
> Am I missing something?

Thanks for pointing this out. It was a quick fix

**Review by svenjens — APPROVED** [review]

**Review by afjlambert — APPROVED** [review]

**Review by svenjens — APPROVED** [review]

**Pull request merged**
