### PR TITLE
fix: Update last packages

### PR DESCRIPTION
**Pull request by afjlambert**

### CODE REVIEW

**Review by robinpiets — CHANGES_REQUESTED** [review]
waajooo, so much upgrades...

and tests are failing

**Comment by afjlambert** [comment]
Please try again.

**Comment by afjlambert** [comment]
bump @robinpiets

**Review by robinpiets — APPROVED** [review]
I removed @datapunt/asc-core package and updated the imports. Okay with that @afjlambert?

**Pull request merged**
