### PR TITLE
Added compressed-size-action github action (Netlify branch)

### PR DESCRIPTION
**Pull request by robinpiets**
Added Compressed Size (for Netlify branch) to see the total size changes for the PR.
URL: https://github.com/marketplace/actions/compressed-size-action

Please merge

### CODE REVIEW

**Comment by robinpiets** [comment]
Failing test is because of the original branch, not because of this one

**Review by svenjens — APPROVED** [review]

**Comment by afjlambert** [comment]
Total size: 0 bytes?

**Review by afjlambert — CHANGES_REQUESTED** [review]
Can you explain why you did this PR onto dockereless-hosting?
Why use build:netlify instead of the regular build?
The actual size seems to be 0 bytes. Can you explain why this is?

**Comment by robinpiets** [comment]
/package.json get new `build`: `lerna run build`

**Comment by robinpiets** [comment]
Also update to v2

**Comment by robinpiets** [comment]
Closing this because #182 is a better fix

**Pull request closed without merging**
